install:
  - cinst gitversion.portable -y

platform: Any CPU
configuration: Release

before_build:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - nuget restore Source/QuantityTypes.sln
  - gitversion /l console /output buildserver /updateAssemblyInfo

build:
  project: Source/QuantityTypes.sln
  verbosity: minimal

after_build:
  - NuGet pack Source\QuantityTypes\QuantityTypes.nuspec -version "%GitVersion_NuGetVersion%"
  - NuGet pack Source\QuantityTypes.Csv\QuantityTypes.Csv.nuspec -version "%GitVersion_NuGetVersion%"

artifacts:
  - path: Source/QuantityTypes/bin/Release
    name: QuantityTypes-$(GitVersion_SemVer)
    type: zip
  - path: '*.nupkg'
    name: QuantityTypes-$(GitVersion_SemVer)
    type: zip
